---
title: AFRISTAT Big Data
author: "Insee"
date: "11/08/2023"
date-format: "D MMMM YYYY"
slide-number: true
lang: fr-FR
# for blind readers:
slide-tone: false
chalkboard: # press the B key to toggle chalkboard
  theme: whiteboard
# uncomment to use the multiplex mode:
# multiplex: true
format:
  onyxia-revealjs:
    incremental: true
    output-file: index.html
controls: true
css: style/custom.css
from: markdown+emoji
ascii: true
execute: 
  echo: false
  warning: false
---

## Big data : une définition pragmatique

- Une notion aux [**contours flous**]{.orange} à désacraliser

- Une [**définition pragmatique**]{.orange}
  - [**Volumétrie**]{.blue2} : difficiles à traiter sur des environnements usuels
  - [**Variété**]{.blue2} : nécessite des méthodes de traitement non-standard
  - Généralement [**non-collectée à des fins de statistique publique**]{.blue2}

## Big data : une transition en  2 temps

- [**Court terme**]{.orange} :
  - Adopter des technologies [**innovantes**]{.blue2} sans nécessité d'infrastructure
  - Mettre une [***sandbox***]{.blue2} à disposition pour l'innovation
  - Privilégier sources de données [**internes**]{.blue2}
  - Commencer par des [**projets pilotes**]{.blue2} pour prouver l'intérêt

- [**Moyen terme**]{.orange} :
  - Développement d'une [**infrastructure Big Data**]{.blue2} adaptée
  - Mise en place de [**partenariats**]{.blue2} avec acteurs privés

## Des outils à adapter

- Transition vers des [**outils informatiques adaptés**]{.orange}
  - Format de fichier : [**Parquet**]{.blue2}
  - Traitement de données volumineuses : [**Arrow**]{.blue2} & [**DuckDB**]{.blue2}
  - Traitement de données massives : [**Spark**]{.blue2}

. . .

::: {.callout-tip title="Recommendations"}
- Transitionner vers des [**langages et outils open-source**]{.blue2} (R, Python)
- Appliquer ces technologies à un [**projet**]{.blue2} concret
:::  

## De statisticien à data scientist

- [**Veille méthodologique**]{.orange}
  - Traitement des [**données non-structurées**]{.blue2}
  - Méthodes de [**machine learning**]{.blue2}

- Acculturation aux [**outils informatiques**]{.orange}
  - [**Calcul distribué**]{.blue2}
  - Outils pour la [**mise en production**]{.blue2}

. . .

::: {.callout-tip title="Recommendations"}
- Favoriser la [**formation**]{.blue2} et [**l'auto-formation**]{.blue2}
- Liens avec les [**écoles de formation**]{.blue2}
- [Catalogue de formation du SSP Cloud](https://www.sspcloud.fr/formation)
::: 


